# Generated by Django 5.2.3 on 2025-07-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('admission_number', models.TextField(unique=True)),
                ('branch', models.TextField()),
                ('year', models.IntegerField()),
                ('contact_number', models.BigIntegerField()),
                ('component_name', models.TextField()),
                ('componentissue_date', models.TextField()),
                ('componentdue_date', models.TextField()),
                ('faculty_referred', models.TextField()),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
